[project]
name = "qtbug-gerrit-change-scraper"
version = "0.0.1"
description = "Script for scraping commits from QTBUGs"
dependencies = [
    "bs4>=0.0.2",
    "requests>=2.32.3",
]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"
